# Jekyll plugins
gems:
  - jekyll-feed

# Site settings
name: Java Küche
url: http://java-kuche.org
description: 沖縄のプログラマコミュニティ
twitter: JavaKueche
facebook: JavaKueche
github:
  owner: JavaKueche
#  url: https://github.com/JavaKueche/javakueche.github.io

# Jekyll settings
highlighter: true
permalink: /posts/:title
markdown: kramdown
redcarpet:
  extensions: ['tables', 'autolink', 'no_intra_emphasis']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'vendor']

# Jekyll Feed
feed:
  path: atom.xml
