# Jekyll plugins
#   https://help.github.com/articles/configuring-jekyll-plugins/
plugins:
  # GitHub Pages default plugins
  # Default plugins are enabled by default and cannot be disabled.
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

  # Enable optional plugins
  # To enable an optional plugin, you must add it your _config.yml file.
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Site settings
title: Java Küche
url: http://java-kuche.org
description: 沖縄のプログラマコミュニティ
author:
  twitter: JavaKueche

# Jekyll settings
#   Default: https://help.github.com/articles/configuring-jekyll/
highlighter: true
permalink: /posts/:title
markdown: kramdown
kramdown:
  input: GFM
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'vendor']

# Jekyll Feed
#   https://github.com/jekyll/jekyll-feed
#   https://help.github.com/articles/atom-rss-feeds-for-github-pages/
feed:
  path: atom.xml

# Jekyll SEO tags settings
#   https://github.com/jekyll/jekyll-seo-tag/
logo: /images/logo.jpg
lang: ja_JP
twitter:
  username: JavaKueche
facebook:
  publisher: https://www.facebook.com/javakueche/
github:
  owner: JavaKueche
