# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
title: Java Küche
url: http://java-kuche.org
description: 沖縄のプログラマコミュニティ
image: /images/avatar.jpg
logo: /images/logo.jpg
lang: ja_JP
twitter:
  username: JavaKueche
facebook:
  publisher: https://www.facebook.com/javakueche/
github:
  owner: JavaKueche

# Jekyll settings
highlighter: true
permalink: /posts/:title
markdown: kramdown
kramdown:
  input: GFM
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'vendor']

# Jekyll Feed
feed:
  path: atom.xml
