# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
title: Java Küche
url: http://java-kuche.org
description: 沖縄のプログラマコミュニティ
image: /images/avatar.jpg
lang: ja_JP
twitter: JavaKueche
facebook: JavaKueche
github:
  owner: JavaKueche
#  url: https://github.com/JavaKueche/javakueche.github.io

# Jekyll settings
highlighter: true
permalink: /posts/:title
markdown: kramdown
kramdown:
  input: GFM
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'vendor']

# Jekyll Feed
feed:
  path: atom.xml
